version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0-jammy
    container_name: bwc-academy-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - elearning-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bwc-academy-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/elearning?authSource=admin
      - JWT_SECRET=super-secret-jwt-key-change-in-production
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - elearning-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

networks:
  elearning-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local